services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      LT_HOST: "0.0.0.0"
      LT_PORT: "5000"
      LT_LOAD_ONLY: "zh,en,fr"
      LT_UPDATE_MODELS: "true"
      LT_API_KEYS: "true"
    volumes:
      - lt-models:/home/libretranslate/.local
      - lt-db:/app/db

volumes:
  lt-models:
  lt-db:
